server:
  port: 8888 # Config Server? ?? ??

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          # ?? Git ??? ??
          uri: https://github.com/my-org/ecommerce-config-repo # ??? ??? ??
          # (Private ???? ?? username, password ? ??)
          default-label: main # ?? ???
