server:
  port: 8080 # ?????? MSA? ?? ??? 8080?? ??

spring:
  application:
    name: gateway-service # ??? ?? ??

  cloud:
    gateway:
      server:
        webflux:
          routes:  # ??? ?? ?? (routes? List ??)
            # --- ?? ??? ??? ---
                    - id: member-service-route # 4. ? ???? ?? ID

                      # ? ???? ????? ??? ??? ??? URI
                      # (?: ??? ????. ??? ??? ?????? ?? 'lb://MEMBER-SERVICE'? ?? ??)
                      uri: http://localhost:8081

                      # ? ???? ??? ?? (Predicates)
                      predicates:
                        - Path=/api/v1/members/** # /api/v1/members/? ???? ?? ??

                      # ?? ????? ???? ?? (?? ????? ?? ?)
                      # ?? ???? ???? ???? ?? ?? ???? ??
                        # ?????? ?? member-service? ???? member-service? ?? ??? 'X-Request-Source: gateway-service' ? ??? ?? ??? ?? ?
                        # ??? ?????? ?? ???? 'X-Response-Source: gateway-service' ? ??? ? ??
                      # name: ?? ??, args: ??? ??? ?? (key:value)
                      filters:
                        - name: AddRequestHeader
                        - args:
                            name : X-Request-Source # ??? key
                            value : gateway-service # ??? value

                        # ???(??)
                        - AddResponseHeader=X-Response-Source, gateway-service

                    # --- ?? ??? ??? ---
                    - id: product-service-route
                      uri: http://localhost:8082
                      predicates:
                        - Path=/api/v1/products/**

                    # --- ?? ??? ??? ---
                    - id: order-service-route
                      uri: http://localhost:8083
                      predicates:
                        - Path=/api/v1/orders/**
