server:
  port: 8081 # ?? ??? ?? 8081? ?? (????? ?? 8080)

spring:
  application:
    name: member-service # Eureka? ??? '??? ??'. ???? ??(MEMBER-SERVICE)
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # Consul? ? ??? ????? ???? ?? ??? ??
        health-check-path: /actuator/health
        # ?? ?? ??
        health-check-interval: 15s
        # ??? ID? ???? ??? ?? ????? ?? ???? ?? ??
        instance-id: ${spring.application.name}:${random.value}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka ??(?)? ??.
  instance:
    prefer-ip-address: true # IP ??? ????? ??

# Actuator? health ????? ???
management:
  endpoints:
    web:
      exposure:
        include: health,info