server:
  port: 8081 # ?? ??? ?? 8081? ?? (????? ?? 8080)

spring:
  application:
    name: member-service # Eureka? ??? '??? ??'. ???? ?? (MEMBER-SERVICE)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka ??(?)? ??.
  instance:
    prefer-ip-address: true # IP ??? ????? ??